from typing import List
from models.schemas import DecisionInput, DecisionOutput, RecommendationOption
from agents.base import PipelineStage

class DecisionIntelligenceStage(PipelineStage):
    """
    Stage 10: Decision Intelligence Module
    Synthesizes IRAC reasoning, trust metrics, case breakthroughs, and statutory context into:
    - Primary actionable recommendation
    - Ranked alternative options with Pros, Cons, and Risk Level
    - Summary of actionable breakthroughs
    - Statutory caveats and legal disclaimers
    """

    @property
    def stage_id(self) -> str:
        return "decision"

    @property
    def stage_name(self) -> str:
        return "Decision Intelligence Module"

    async def process(self, input_data: DecisionInput) -> DecisionOutput:
        analysis = input_data.reasoning.analysis
        trust = input_data.trust
        breakthroughs = input_data.reasoning.breakthroughs
        
        primary_rec = (
            f"Primary Action: Relying on the established constitutional and statutory protections, "
            f"document the specific violation of {analysis.rule} and issue a formal representation or legal notice. "
            f"If state authorities fail to remedy within statutory timelines, invoke judicial remedies under Article 32 (Supreme Court), "
            f"Article 226 (High Court), or Section 528 BNSS / Section 482 CrPC."
        )

        alternatives: List[RecommendationOption] = [
            RecommendationOption(
                title="Writ Petition under Article 226 (High Court)",
                description="Approach the jurisdictional High Court seeking a writ of Habeas Corpus, Mandamus, or Certiorari.",
                pros=["Broader jurisdiction than Supreme Court (covers legal rights beyond fundamental rights)", "Faster geographical access"],
                cons=["Subject to alternate statutory remedy doctrine", "May face court backlogs"],
                risk_level="Low",
                estimated_timeline="1 to 4 weeks"
            ),
            RecommendationOption(
                title="Quashing Petition under Section 528 BNSS / 482 CrPC",
                description="Petition the High Court to quash the FIR or Charge Sheet on grounds of manifest illegality or absence of prima facie offence.",
                pros=["Stops criminal trial at threshold", "Protects against arrest and reputational damage"],
                cons=["High Court exercises jurisdiction sparingly", "Requires clear demonstration of abuse of process"],
                risk_level="Medium",
                estimated_timeline="2 to 6 months"
            ),
            RecommendationOption(
                title="Direct Supreme Court Petition under Article 32",
                description="Directly invoke the fundamental right to constitutional remedies before the Supreme Court of India.",
                pros=["Highest judicial authority", "Establishes nationwide binding precedent"],
                cons=["Supreme Court routinely directs petitioners to approach High Court first under Article 226", "Higher litigation costs"],
                risk_level="High",
                estimated_timeline="2 to 8 weeks"
            )
        ]

        disclaimers = [
            "This analysis is generated by NyayaAI's 13-stage federated multi-agent pipeline and is intended for informational and research purposes.",
            "It does not constitute a formal advocate-client relationship under the Advocates Act, 1961. Consult an enrolled legal practitioner for case representation.",
            "Verify current statutory notifications, high court bench rules, and limitation periods applicable to your specific jurisdiction."
        ]

        return DecisionOutput(
            primary_recommendation=primary_rec,
            alternatives=alternatives,
            breakthroughs_summary=breakthroughs,
            disclaimers=disclaimers
        )
